### ISSUE TITLE
segfault in sort_by_cell()

### ISSUE THREAD

**Issue by Zherdev** [Markus-Goetz/hpdbscan#3]
Hello!

Running HPDBSCAN results in segmentation fault.

Dataset: [SCADI](https://archive.ics.uci.edu/ml/datasets/SCADI). 
Converted to h5f: https://cloud.mail.ru/public/e7ux/HykrvAgmM

Platform LSF log with HPDBSCAN stdout:

```
Sender: LSF System <lsfadmin@polus-c4-ib.bmc.hpc.cs.msu.ru>
...
Started at Sat Jul 10 21:30:59 2021
Terminated at Sat Jul 10 21:31:04 2021
Results reported at Sat Jul 10 21:31:04 2021

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
# this file was automaticly created by mpisubmit.pl script for edu-cmc-sqi20-05 #
#BSUB -n 1
#BSUB -W 00:15
#BSUB -o hpdbscan.%J.out
#BSUB -e hpdbscan.%J.err
OMP_NUM_THREADS=1 mpiexec ./hpdbscan -t 1 -i /home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/ClusterLog_HPDBSCAN/ClusterLog/test/scadi.h5 --input-dataset DBSCAN -o data.h5 --output-dataset CLUSTERS -e 1.3 -m 2

------------------------------------------------------------

Exited with exit code 139.

Resource usage summary:

    CPU time :                                   1.32 sec.
    Max Memory :                                 119 MB
    Average Memory :                             79.67 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              5
    Max Threads :                                13
    Run time :                                   9 sec.
    Turnaround time :                            5 sec.

The output (if any) follows:

Computing cell space
        Computing dimensions...[OK] in 0.000053
        Computing cells...     [OK] in 0.000047
        Sorting points...

PS:

Read file <hpdbscan.765884.err> for stderr output of this job.
```

Platfrom LSF error log with HPDBSCAN staderr:

```
[polus-c4-ib:94545:0:94545] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x3fab4042367150cd)
==== backtrace ====
 0 0x00000000000452c4 ucs_debug_cleanup()  ???:0
 1 0x0000000000013f30 GOMP_parallel()  ???:0
 2 0x00000000100554a0 SpatialIndex<double>::sort_by_cell()  /polusfs/home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/py/highly/gcc9/hpdbscan/include/spatial_index.h:200
 3 0x0000000010072224 SpatialIndex<double>::SpatialIndex()  /polusfs/home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/py/highly/gcc9/hpdbscan/include/spatial_index.h:593
 4 0x0000000010073498 HPDBSCAN::cluster<double>()  /polusfs/home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/py/highly/gcc9/hpdbscan/include/hpdbscan.h:373
 5 0x0000000010073ef0 HPDBSCAN::cluster()  /polusfs/home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/py/highly/gcc9/hpdbscan/include/hpdbscan.h:349
 6 0x000000001000719c main()  /polusfs/home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/py/highly/gcc9/hpdbscan/src/cli.cpp:94
 7 0x0000000000024980 generic_start_main.isra.0()  libc-start.c:0
 8 0x0000000000024b74 __libc_start_main()  ???:0
===================
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node polus-c4-ib exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

GDB core dump:

```
GNU gdb (GDB) Red Hat Enterprise Linux 8.3-3.el7
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "ppc64le-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./hpdbscan...
[New LWP 94545]
[New LWP 94550]
[New LWP 94546]
[New LWP 94547]

warning: .dynamic section for "/lib64/libsz.so.2" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libstdc++.so.6" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libgomp.so.1" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libgcc_s.so.1" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libaec.so.0" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/usr/lib64/libnuma.so.1" is not at the expected address (wrong library or version mismatch?)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./hpdbscan -t 1 -i /home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/ClusterLog_HPDBS'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000010050974 in std::_Hashtable<unsigned long, std::pair<unsigned long const, std::atomic<unsigned long> >, std::allocator<std::pair<unsigned long const, std::atomic<un
signed long> > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::
__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node (__code=0, __k=@0x3ffffc13dbe8: 0, __n=0, this=0x3ffffc13dd28)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/hashtable.h:1532
1532        _Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal,
[Current thread is 1 (Thread 0x100000049500 (LWP 94545))]
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7_4.2.ppc64le hdf5-1.8.12-12.el7.ppc64le libaec-1.0.2-1.el7.ppc64le libgcc-4.8.5-44.el7.ppc64le libgomp-4.8.5
-44.el7.ppc64le libibcm-41mlnx1-OFED.4.1.0.1.0.43101.ppc64le libibverbs-41mlnx1-OFED.4.3.0.1.8.43101.ppc64le libmlx4-41mlnx1-OFED.4.1.0.1.0.43101.ppc64le libmlx5-41mlnx1-OFED.4.3
.0.2.1.43101.ppc64le libnl3-3.2.28-4.el7.ppc64le librdmacm-41mlnx1-OFED.4.2.0.1.3.43101.ppc64le librxe-41mlnx1-OFED.4.1.0.1.7.43101.ppc64le libstdc++-4.8.5-44.el7.ppc64le numactl
-libs-2.0.9-7.el7.ppc64le ucx-1.3.0-1.43101.ppc64le zlib-1.2.7-17.el7.ppc64le
```

bt:

```
(gdb) bt
#0  0x0000000010050974 in std::_Hashtable<unsigned long, std::pair<unsigned long const, std::atomic<unsigned long> >, std::allocator<std::pair<unsigned long const, std::atomic<unsigned long> > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node (__code=0, __k=@0x3ffffc13dbe8: 0, __n=0, this=0x3ffffc13dd28)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/hashtable.h:1532
#1  std::_Hashtable<unsigned long, std::pair<unsigned long const, std::atomic<unsigned long> >, std::allocator<std::pair<unsigned long const, std::atomic<unsigned long> > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_node (__c=0, __key=@0x3ffffc13dbe8: 0, __bkt=0, this=0x3ffffc13dd28)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/hashtable.h:655
#2  std::__detail::_Map_base<unsigned long, std::pair<unsigned long const, std::atomic<unsigned long> >, std::allocator<std::pair<unsigned long const, std::atomic<unsigned long> > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::operator[] (this=0x3ffffc13dd28, __k=@0x3ffffc13dbe8: 0)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/hashtable_policy.h:697
#3  0x0000000010055154 in std::unordered_map<unsigned long, std::atomic<unsigned long>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::atomic<unsigned long> > > >::operator[] (__k=<optimized out>, this=<optimized out>) at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/unordered_map.h:984
#4  SpatialIndex<double>::_ZN12SpatialIndexIdE12sort_by_cellEv._omp_fn.0(void) ()
    at /polusfs/home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/py/highly/gcc9/hpdbscan/include/spatial_index.h:204
#5  0x0000100000853f30 in GOMP_parallel () from /lib64/libgomp.so.1
#6  0x00000000100554a0 in SpatialIndex<double>::sort_by_cell (this=0x3ffffc13e000)
    at /polusfs/home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/py/highly/gcc9/hpdbscan/include/spatial_index.h:195
#7  0x0000000010072224 in SpatialIndex<double>::SpatialIndex (this=0x3ffffc13e000, data=..., epsilon=<optimized out>) at /opt/rh/devtoolset-9/root/usr/include/c++/9/ostream:621
#8  0x0000000010073498 in HPDBSCAN::cluster<double> (this=0x3ffffc13e4d0, dataset=..., threads=<optimized out>)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/basic_ios.h:390
#9  0x0000000010073ef0 in HPDBSCAN::cluster (this=0x3ffffc13e4d0, path=..., dataset=..., threads=<optimized out>)
    at /polusfs/home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/py/highly/gcc9/hpdbscan/include/hpdbscan.h:349
#10 0x000000001000719c in main (argc=<optimized out>, argv=<optimized out>) at /polusfs/home_edu/edu-cmc-sqi20/edu-cmc-sqi20-05/my/py/highly/gcc9/hpdbscan/include/cxxopts.h:838
```

Tools:

```sh
$ mpic++ --version
g++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)

$ mpiexec --version
mpiexec (OpenRTE) 4.0.0
```

**Comment by Markus-Goetz** [comment]
Hi @Zherdev,

thanks for raising this issue. I would have to look into this problem. At the moment I am quite busy with other things. However, I hope to get it done soonish.

**Comment by Zherdev** [comment]
Thanks for the quick response! Waiting for fix :)

**Comment by Zherdev** [comment]
Hello, @Markus-Goetz 

We have been working on the HPC clustering at the Moscow State University and have conducted a study in which some parallel clustering algorithms are considered. One of the algorithms is HPDBSCAN and this issue is also mentioned. You seem to be interested in this topic, so I think you might honor us taking a look at this research.

[Parallelizing of the DBSCAN algorithm in the ClusterLogs framework, International Journal of Modern Physics A Vol. 37, No. 01, 2150247 (2022)](https://www.worldscientific.com/doi/abs/10.1142/S0217751X2150247X)

Sincerely, Zherdev

**Comment by Markus-Goetz** [comment]
Hi @Zherdev ,

thanks for making me aware of your research and the downstream usage of HPDBSCAN. As it currently stands I am busy with other things, hence, also the reason why I did not work on the issue you raised.
